// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uke17G1XV5ahw-tzrmtwYxh9NGuCKRk',
    appId: '1:17453947796:web:e49c7461e6350929e5cd81',
    messagingSenderId: '17453947796',
    projectId: 'taskmasterapp-e3ee2',
    authDomain: 'taskmasterapp-e3ee2.firebaseapp.com',
    storageBucket: 'taskmasterapp-e3ee2.firebasestorage.app',
    measurementId: 'G-95DKBTPCW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvruSQVMt0hH3odQbQYDPVSoSHh5OQtRk',
    appId: '1:17453947796:android:6d3c22d619d24d58e5cd81',
    messagingSenderId: '17453947796',
    projectId: 'taskmasterapp-e3ee2',
    storageBucket: 'taskmasterapp-e3ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXeXHyROs2pVHoILOZ2CMM0g8-jCEmIik',
    appId: '1:17453947796:ios:c96af253da48b7d6e5cd81',
    messagingSenderId: '17453947796',
    projectId: 'taskmasterapp-e3ee2',
    storageBucket: 'taskmasterapp-e3ee2.firebasestorage.app',
    iosBundleId: 'com.example.taskMasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXeXHyROs2pVHoILOZ2CMM0g8-jCEmIik',
    appId: '1:17453947796:ios:c96af253da48b7d6e5cd81',
    messagingSenderId: '17453947796',
    projectId: 'taskmasterapp-e3ee2',
    storageBucket: 'taskmasterapp-e3ee2.firebasestorage.app',
    iosBundleId: 'com.example.taskMasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3uke17G1XV5ahw-tzrmtwYxh9NGuCKRk',
    appId: '1:17453947796:web:7a2ad38b5f1f24fae5cd81',
    messagingSenderId: '17453947796',
    projectId: 'taskmasterapp-e3ee2',
    authDomain: 'taskmasterapp-e3ee2.firebaseapp.com',
    storageBucket: 'taskmasterapp-e3ee2.firebasestorage.app',
    measurementId: 'G-QGYBN3RLNJ',
  );

}